web:
  hostname: web
  container_name: web
  build: ./web
  ports:
    - "80:80"
  links:
    - app

app:
  hostname: app
  container_name: app
  build: ./app
  volumes:
    - "./server:/root/app"
  expose:
    - "3000"
  links:
    - db

db:
  hostname: db
  container_name: db
  build: ./database
  volumes:
    - "/data/db:/data/db"
  expose:
    - "27017"
  command:
    - "/usr/bin/mongod"
